### ISSUE TITLE
Untrusted identity

### ISSUE THREAD

**Issue by enzobrunii** [joaoricardo000/whatsapp-bot-seed#8]
I get this today when i test the new ver.

[ERROR][2015-10-29 21:00:17,565] Untrusted identity!!
[WARNING][2015-10-29 21:00:17,565] Ignoring message with untrusted identity

Yesterday its works fine but now i got this

**Comment by joaoricardo000** [comment]
That is a known Yowsup problem. This usually happens when some user reinstall the whatsapp app.

To fix this, just delete the yowsup folder (normally at ```~/.yowsup/<PHONENUMBER>```
When you restart the server, the encryption keys will be generated again, and the problem will be solved.
Actually deleting the ```.yowsup``` folder will solve most of issues...
